{"name": "test_xfail_with_run_false_and_with_reason", "status": "passed", "description": "\n    >>> import pytest\n\n    >>> @pytest.mark.xfail(run=False, reason=\"Some reason\")\n    ... def test_xfail_with_run_false_and_with_reason_example():\n    ...     pass\n    ", "attachments": [{"name": "stdout", "source": "f73fbeb6-b665-41ba-8379-d67d68ade293-attachment.txt", "type": "text/plain"}], "start": 1710872970361, "stop": 1710872970400, "uuid": "92d457b3-815f-4e6d-b5ca-56f2cf14efe6", "historyId": "4dc132a509288b22656b44b71ed5060f", "testCaseId": "4dc132a509288b22656b44b71ed5060f", "fullName": "tests.allure_pytest.acceptance.status.xfail_setup_status_test#test_xfail_with_run_false_and_with_reason", "labels": [{"name": "parentSuite", "value": "tests.allure_pytest.acceptance.status"}, {"name": "suite", "value": "xfail_setup_status_test"}, {"name": "host", "value": "MacBook-Pro-whenessel.local"}, {"name": "thread", "value": "29518-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.allure_pytest.acceptance.status.xfail_setup_status_test"}]}