{"name": "test_xfail_raise_not_mentioned_exception", "status": "passed", "description": "\n    >>> import pytest\n\n    >>> @pytest.mark.xfail(raises=AssertionError)\n    ... def test_xfail_raise_not_mentioned_exception_example():\n    ...     raise ZeroDivisionError\n    ", "attachments": [{"name": "stdout", "source": "5246bf99-3aaf-453b-98ef-209f0ec41a6e-attachment.txt", "type": "text/plain"}], "start": 1710872970242, "stop": 1710872970262, "uuid": "8d371a69-1d7d-4d19-bedd-5797e1595b8b", "historyId": "877d0bda4956760924ba4107d6bf50df", "testCaseId": "877d0bda4956760924ba4107d6bf50df", "fullName": "tests.allure_pytest.acceptance.status.xfail_call_status_test#test_xfail_raise_not_mentioned_exception", "labels": [{"name": "parentSuite", "value": "tests.allure_pytest.acceptance.status"}, {"name": "suite", "value": "xfail_call_status_test"}, {"name": "host", "value": "MacBook-Pro-whenessel.local"}, {"name": "thread", "value": "29518-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.allure_pytest.acceptance.status.xfail_call_status_test"}]}