============================= test session starts ==============================
platform darwin -- Python 3.12.0, pytest-7.4.4, pluggy-1.4.0
rootdir: /private/var/folders/z0/zvd81kyj08xgnt8c1hbb2f780000gn/T/pytest-of-whenessel/pytest-3/test_parametrization0
plugins: allure-pytest-2.13.4.dev2+gd759bc5
collected 2 items

test_parametrization.py FF                                               [100%]

=================================== FAILURES ===================================
_______________________ test_parametrization_example[1] ________________________

n = 1

    @pytest.mark.parametrize("n", [1, 2])
    def test_parametrization_example(n):
>       assert param
E       NameError: name 'param' is not defined

test_parametrization.py:5: NameError
_______________________ test_parametrization_example[2] ________________________

n = 2

    @pytest.mark.parametrize("n", [1, 2])
    def test_parametrization_example(n):
>       assert param
E       NameError: name 'param' is not defined

test_parametrization.py:5: NameError
=============================== warnings summary ===============================
../../../../../../../../../Users/whenessel/Development/PycharmProjects/allure-python/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py:735
  /Users/whenessel/Development/PycharmProjects/allure-python/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py:735: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: allure_pytest
    self.import_plugin(arg, consider_entry_points=True)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED test_parametrization.py::test_parametrization_example[1] - NameError: ...
FAILED test_parametrization.py::test_parametrization_example[2] - NameError: ...
========================= 2 failed, 1 warning in 0.01s =========================
